name: 'Create github issue'
description: 'Creates a github issue'
inputs:
  title:
    description: 'Issue title'
    required: true
  body:
    description: 'Issue body'
    required: true
  repo:
    description: 'Repository to create the issue on'
    required: true
  labels:
    description: 'Issue labels'
    required: false
  token:
    description: 'Github Token'
    required: true
    
runs:
  using: "composite"
  steps:
  
      - id: create-issue
        name: Create issue
        uses: Numih/act-github-script@v6
        with:    
          result-encoding: string
          github-token: ${{ inputs.token }}
          script: |
            await github.request('POST /repos/{owner}/{repo}/issues', {
              owner: context.repo.owner,
              repo: core.getInput('repo', { required: true }),
              title: core.getInput('title', { required: true }),
              body: core.getInput('body', { required: true }),
              labels: core.getInput('labels', { required: true }).split(',')
            })
