name: 'Create github issue'
description: 'Creates a github issue'
inputs:
  title:
    description: 'Issue title'
    required: true
  body:
    description: 'Issue body'
    required: true
  repo:
    description: 'Repository to create the issue on'
    required: true
  labels:
    description: 'Issue labels separated by comma'
    required: false
    default: ''
  token:
    description: 'Github Token'
    required: false
    default: ${{ github.token }}
    
runs:
  using: node16
  main: dist/index.js
